apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: davidschmidt38/ambulance-ufe
  newName: davidschmidt38/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20240319.1027 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: milung/ufe-controller
  newName: milung/ufe-controller # {"$imagepolicy":  "wac-hospital:ufe-controller:name"}
  newTag: 1.7.3 # {"$imagepolicy": "wac-hospital:ufe-controller:tag"}
- name: davidschmidt38/ambulance-wl-webapi
  newName: davidschmidt38/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20240327.0757 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
